package com.skillstorm.hotelreservationsystem.models;

import java.time.Instant;
import java.util.Collection;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * Represents an employee in the hotel reservation system.
 * <p>
 * This class maps to the "employees" collection in MongoDB. It implements Spring Security's
 * {@code UserDetails} interface to enable authentication and authorization for staff members.
 * Employees have unique IDs, email addresses, and roles that determine their access levels
 * within the system.
 * </p>
 * 
 * @author SkillStorm
 * @version 1.0
 */
@Document(collection = "employees")
public class Employee implements UserDetails {

    /**
     * The unique identifier for the employee.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The unique employee ID assigned by the organization.
     * This is separate from the MongoDB-generated ID and serves as a business identifier.
     */
    @Indexed(unique = true)
    private String employeeId;

    /**
     * The employee's email address.
     * Used as the username for authentication and must be unique.
     */
    @Indexed(unique = true)
    private String email;

    /**
     * The hashed password for authentication.
     * Stored using a secure hashing algorithm (e.g., BCrypt).
     */
    private String passwordHash;

    /**
     * List of roles assigned to the employee.
     * Common roles include "ROLE_ADMIN" and "ROLE_EMPLOYEE".
     */
    private List<String> roles; // ROLE_ADMIN, ROLE_EMPLOYEE

    /**
     * Indicates whether the employee account is currently active.
     * Inactive accounts cannot authenticate.
     */
    private boolean isActive = true;

    /**
     * The timestamp when the employee account was created.
     */
    private Instant createdAt = Instant.now();

    /**
     * The timestamp of the employee's last successful login.
     * May be null if the employee has never logged in.
     */
    private Instant lastLogin;

    /**
     * Returns the authorities (roles) granted to the employee.
     * Converts the list of role strings to Spring Security {@code GrantedAuthority} objects.
     *
     * @return A collection of granted authorities.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return roles.stream()
                .map(SimpleGrantedAuthority::new)
                .toList();
    }

    /**
     * Returns the password used to authenticate the employee.
     *
     * @return The hashed password.
     */
    @Override
    public String getPassword() {
        return passwordHash;
    }

    /**
     * Returns the username used to authenticate the employee.
     * In this implementation, the email address serves as the username.
     *
     * @return The email address.
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Indicates whether the employee's account has expired.
     *
     * @return Always returns true (accounts do not expire).
     */
    @Override 
    public boolean isAccountNonExpired() { 
        return true; 
    }
    
    /**
     * Indicates whether the employee's account is locked.
     *
     * @return Always returns true (accounts are never locked).
     */
    @Override 
    public boolean isAccountNonLocked() { 
        return true; 
    }
    
    /**
     * Indicates whether the employee's credentials (password) have expired.
     *
     * @return Always returns true (credentials do not expire).
     */
    @Override 
    public boolean isCredentialsNonExpired() { 
        return true; 
    }
    
    /**
     * Indicates whether the employee's account is enabled.
     *
     * @return True if the account is active; false otherwise.
     */
    @Override 
    public boolean isEnabled() { 
        return isActive; 
    }

    /**
     * Gets the unique identifier of the employee.
     *
     * @return The MongoDB ObjectId as a String.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the employee.
     *
     * @param id The new MongoDB ObjectId.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the employee's business ID.
     *
     * @return The employee ID.
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * Sets the employee's business ID.
     *
     * @param employeeId The new employee ID.
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * Gets the employee's email address.
     *
     * @return The email address.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the employee's email address.
     *
     * @param email The new email address.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the hashed password.
     *
     * @return The password hash.
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * Sets the hashed password.
     *
     * @param passwordHash The new password hash.
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * Gets the list of roles assigned to the employee.
     *
     * @return The list of role strings.
     */
    public List<String> getRoles() {
        return roles;
    }

    /**
     * Sets the list of roles for the employee.
     *
     * @param roles The new list of role strings.
     */
    public void setRoles(List<String> roles) {
        this.roles = roles;
    }

    /**
     * Checks if the employee account is active.
     *
     * @return True if active; false otherwise.
     */
    public boolean isActive() {
        return isActive;
    }

    /**
     * Sets the active status of the employee account.
     *
     * @param isActive True to activate the account; false to deactivate.
     */
    public void setActive(boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * Gets the timestamp when the account was created.
     *
     * @return The creation timestamp.
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the timestamp when the account was created.
     *
     * @param createdAt The creation timestamp.
     */
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets the timestamp of the last login.
     *
     * @return The last login timestamp, or null if never logged in.
     */
    public Instant getLastLogin() {
        return lastLogin;
    }

    /**
     * Sets the timestamp of the last login.
     *
     * @param lastLogin The last login timestamp.
     */
    public void setLastLogin(Instant lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * Checks if this Employee is equal to another object.
     * Equality is determined by comparing employee IDs.
     *
     * @param o The object to compare with.
     * @return True if the objects are equal; false otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Employee)) return false;
        Employee other = (Employee) o;
        return employeeId != null && employeeId.equals(other.employeeId);
    }

    /**
     * Generates a hash code for this Employee.
     * Based on the employee ID.
     *
     * @return The hash code.
     */
    @Override
    public int hashCode() {
        return employeeId != null ? employeeId.hashCode() : 0;
    }

    /**
     * Returns a string representation of the Employee.
     *
     * @return A string containing employee details.
     */
    @Override
    public String toString() {
        return "Employee [id=" + id + ", employeeId=" + employeeId + ", email=" + email + ", roles=" + roles + ", isActive=" + isActive + ", createdAt=" + createdAt + "]";
    }
}