package com.skillstorm.hotelreservationsystem.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDate;

/**
 * Represents a booking transaction within the hotel reservation system.
 * <p>
 * This class maps to the "reservations" collection in MongoDB. It links a specific {@code User}
 * to a specific {@code Room} for a defined date range. It also tracks the financial status
 * of the booking via Stripe payment intents.
 * </p>
 * * @author SkillStorm
 * @version 1.0
 */
@Document(collection = "reservations")
public class Reservation {

    /**
     * The unique identifier for the reservation.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The unique identifier of the user who made the reservation.
     * This references the "_id" field in the "users" collection.
     */
    private String userId; 

    /**
     * The unique identifier of the room being booked.
     * This references the "_id" field in the "rooms" collection.
     */
    private String roomId; 

    /**
     * The scheduled arrival date for the guest.
     */
    private LocalDate checkIn;

    /**
     * The scheduled departure date for the guest.
     */
    private LocalDate checkOut;

    /**
     * The number of guests staying in the room.
     */
    private int guestCount;

    /**
     * The total cost of the reservation.
     * Calculated based on the room's price per night multiplied by the duration of the stay.
     */
    private double totalPrice;

    /**
     * The current lifecycle state of the reservation (e.g., PENDING, CONFIRMED).
     */
    private ReservationStatus status;
    
    /**
     * The unique transaction identifier provided by the payment processor (Stripe).
     * Used to verify that payment has been completed before confirming the booking.
     */
    private String paymentIntentId;

    // --- Enum for Status ---

    /**
     * Enumeration representing the possible states of a reservation.
     */
    public enum ReservationStatus {
        /**
         * The reservation has been drafted but payment has not yet been processed.
         */
        PENDING,

        /**
         * Payment has been verified and the room is officially booked.
         */
        CONFIRMED,

        /**
         * The reservation was cancelled by the user or admin before check-in.
         */
        CANCELLED,

        /**
         * The reservation was cancelled and the payment has been returned to the user.
         */
        REFUNDED
    }

    // --- Overrides ---

    /**
     * Returns a string representation of the Reservation.
     *
     * @return A string containing all reservation details including IDs, dates, and status.
     */
    @Override
    public String toString() {
        return "Reservation [id=" + id + ", userId=" + userId + ", roomId=" + roomId + ", checkIn=" + checkIn
                + ", checkOut=" + checkOut + ", guestCount=" + guestCount + ", totalPrice=" + totalPrice + ", status="
                + status + ", paymentIntentId=" + paymentIntentId + "]";
    }

    /**
     * Generates a hash code for this Reservation.
     * Based on all fields including IDs, dates, price, and payment info.
     *
     * @return The hash code.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((userId == null) ? 0 : userId.hashCode());
        result = prime * result + ((roomId == null) ? 0 : roomId.hashCode());
        result = prime * result + ((checkIn == null) ? 0 : checkIn.hashCode());
        result = prime * result + ((checkOut == null) ? 0 : checkOut.hashCode());
        result = prime * result + guestCount;
        long temp;
        temp = Double.doubleToLongBits(totalPrice);
        result = prime * result + (int) (temp ^ (temp >>> 32));
        result = prime * result + ((status == null) ? 0 : status.hashCode());
        result = prime * result + ((paymentIntentId == null) ? 0 : paymentIntentId.hashCode());
        return result;
    }

    /**
     * Checks if this Reservation is equal to another object.
     * Equality is determined by comparing all fields of the Reservation.
     *
     * @param obj The object to compare with.
     * @return True if the objects are equal; false otherwise.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Reservation other = (Reservation) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        } else if (!userId.equals(other.userId))
            return false;
        if (roomId == null) {
            if (other.roomId != null)
                return false;
        } else if (!roomId.equals(other.roomId))
            return false;
        if (checkIn == null) {
            if (other.checkIn != null)
                return false;
        } else if (!checkIn.equals(other.checkIn))
            return false;
        if (checkOut == null) {
            if (other.checkOut != null)
                return false;
        } else if (!checkOut.equals(other.checkOut))
            return false;
        if (guestCount != other.guestCount)
            return false;
        if (Double.doubleToLongBits(totalPrice) != Double.doubleToLongBits(other.totalPrice))
            return false;
        if (status != other.status)
            return false;
        if (paymentIntentId == null) {
            if (other.paymentIntentId != null)
                return false;
        } else if (!paymentIntentId.equals(other.paymentIntentId))
            return false;
        return true;
    }

    // --- Getters and Setters ---

    /**
     * Gets the unique identifier of the reservation.
     *
     * @return The MongoDB ObjectId as a String.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the reservation.
     *
     * @param id The new MongoDB ObjectId.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the ID of the user who made the reservation.
     *
     * @return The user ID.
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the ID of the user making the reservation.
     *
     * @param userId The new user ID.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Gets the ID of the reserved room.
     *
     * @return The room ID.
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * Sets the ID of the reserved room.
     *
     * @param roomId The new room ID.
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * Gets the check-in date.
     *
     * @return The check-in date.
     */
    public LocalDate getCheckIn() {
        return checkIn;
    }

    /**
     * Sets the check-in date.
     *
     * @param checkIn The new check-in date.
     */
    public void setCheckIn(LocalDate checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * Gets the check-out date.
     *
     * @return The check-out date.
     */
    public LocalDate getCheckOut() {
        return checkOut;
    }

    /**
     * Sets the check-out date.
     *
     * @param checkOut The new check-out date.
     */
    public void setCheckOut(LocalDate checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * Gets the number of guests.
     *
     * @return The guest count.
     */
    public int getGuestCount() {
        return guestCount;
    }

    /**
     * Sets the number of guests.
     *
     * @param guestCount The new guest count.
     */
    public void setGuestCount(int guestCount) {
        this.guestCount = guestCount;
    }

    /**
     * Gets the total price of the reservation.
     *
     * @return The total price.
     */
    public double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the total price of the reservation.
     *
     * @param totalPrice The new total price.
     */
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Gets the current status of the reservation.
     *
     * @return The reservation status (e.g., CONFIRMED, CANCELLED).
     */
    public ReservationStatus getStatus() {
        return status;
    }

    /**
     * Sets the status of the reservation.
     *
     * @param status The new status.
     */
    public void setStatus(ReservationStatus status) {
        this.status = status;
    }

    /**
     * Gets the Stripe Payment Intent ID associated with this booking.
     *
     * @return The payment intent ID.
     */
    public String getPaymentIntentId() {
        return paymentIntentId;
    }

    /**
     * Sets the Stripe Payment Intent ID.
     *
     * @param paymentIntentId The new payment intent ID.
     */
    public void setPaymentIntentId(String paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }
}