package com.skillstorm.hotelreservationsystem.models;

import java.time.Instant;
import java.time.LocalDate;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a booking transaction within the hotel reservation system.
 * <p>
 * This class maps to the "reservations" collection in MongoDB. It links a specific {@code User}
 * to a specific {@code Room} for a defined date range. It also tracks the financial status
 * of the booking via Stripe payment intents.
 * </p>
 * * @author SkillStorm
 * @version 1.0
 */
@Document(collection = "reservations")
public class Reservation {
    

    /**
     * Constructs a new Reservation with the specified details.
     *
     * @param userId The unique identifier of the user making the reservation.
     * @param roomId The unique identifier of the reserved room.
     * @param checkIn The scheduled check-in date.
     * @param checkOut The scheduled check-out date.
     * @param guestCount The number of guests staying in the room.
     * @param totalPrice The total cost of the reservation.
     * @param status The current status of the reservation.
     * @param paymentIntentId The Stripe payment intent identifier.
     */
    public Reservation(String userId, String roomId, LocalDate checkIn, LocalDate checkOut, int guestCount, double totalPrice,
            ReservationStatus status, String paymentIntentId) {
        this.userId = userId;
        this.roomId = roomId;
        this.checkIn = checkIn;
        this.checkOut = checkOut;
        this.guestCount = guestCount;
        this.totalPrice = totalPrice;
        this.status = status;
        this.paymentIntentId = paymentIntentId;
    }

    /**
     * The unique identifier for the reservation.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     *  User who made the reservation
     */
    @Transient
    private User user;

    /**
     * The room that this reservation is for
     */
    @Transient
    private Room room; 

    /**
     * The unique identifier of the user who made the reservation.
     * This is the MongoDB ObjectId of the User document.
     */
    private String userId;
    
    /**
     * The unique identifier of the room being reserved.
     * This is the MongoDB ObjectId of the Room document.
     */
    private String roomId;

    /**
     * The scheduled arrival date for the guest.
     */
    private LocalDate checkIn;

    /**
     * The scheduled departure date for the guest.
     */
    private LocalDate checkOut;

    /**
     * The number of guests staying in the room.
     */
    private int guestCount;

    /**
     * The total cost of the reservation.
     * Calculated based on the room's price per night multiplied by the duration of the stay.
     */
    private double totalPrice;

    /**
     * The current lifecycle state of the reservation (e.g., PENDING, CONFIRMED).
     */
    private ReservationStatus status;
    
    /**
     * The unique transaction identifier provided by the payment processor (Stripe).
     * Used to verify that payment has been completed before confirming the booking.
     */
    private String paymentIntentId;

    /**
     * The payment status of the reservation.
     */
    private PaymentStatus paymentStatus;

    /**
     * Payment transaction details including provider, amount, and status.
     */
    private PaymentTransaction transaction;

    /**
     * The timestamp when the guest checked in.
     */
    private Instant checkedInAt;

    // --- Enum for Status ---

    /**
     * Enumeration representing the possible states of a reservation.
     */
    public enum ReservationStatus {
        /**
         * The reservation has been drafted but payment has not yet been processed.
         */
        PENDING,

        /**
         * Payment has been verified and the room is officially booked.
         */
        CONFIRMED,

        /**
         * The guest has checked in to the reservation.
         */
        CHECKED_IN,

        /**
         * The reservation was cancelled by the user or admin before check-in.
         */
        CANCELLED,

        /**
         * The reservation was cancelled and the payment has been returned to the user.
         */
        REFUNDED,

        /**
         * The reservation happend in the past.
         */
        COMPLETED
    }

    /**
     * Enumeration representing the payment status of a reservation.
     */
    public enum PaymentStatus {
        /**
         * Payment has not yet been processed.
         */
        UNPAID,

        /**
         * Payment has been successfully processed.
         */
        PAID,

        /**
         * Payment has been refunded.
         */
        REFUNDED
    }

    /**
     * Single snapshot record for payment transaction details.
     * Status can be updated to REFUNDED and include refund info if needed.
     * This nested class stores a complete record of a payment transaction for audit purposes.
     */
    public static class PaymentTransaction {
        /**
         * The payment provider name (e.g., "STRIPE").
         */
        private String provider;       // "STRIPE"
        
        /**
         * The unique transaction identifier from the payment provider.
         * Typically uses the paymentIntentId as a stable identifier.
         */
        private String transactionId;  // use paymentIntentId as stable id
        
        /**
         * The transaction amount in cents.
         */
        private long amountCents;
        
        /**
         * The currency code (e.g., "usd").
         */
        private String currency;       // "usd"
        
        /**
         * The transaction status (e.g., "SUCCEEDED", "REFUNDED").
         */
        private String status;         // "SUCCEEDED", "REFUNDED"
        
        /**
         * The timestamp when the payment was processed.
         */
        private Instant paidAt;

        /**
         * The refund identifier from the payment provider.
         * Only populated if the transaction has been refunded.
         */
        private String refundId;
        
        /**
         * The timestamp when the refund was processed.
         * Only populated if the transaction has been refunded.
         */
        private Instant refundedAt;

        /**
         * Gets the payment provider name.
         *
         * @return The provider name.
         */
        public String getProvider() { 
            return provider; 
        }
        
        /**
         * Sets the payment provider name.
         *
         * @param provider The provider name.
         */
        public void setProvider(String provider) { 
            this.provider = provider; 
        }

        /**
         * Gets the transaction identifier.
         *
         * @return The transaction ID.
         */
        public String getTransactionId() { 
            return transactionId; 
        }
        
        /**
         * Sets the transaction identifier.
         *
         * @param transactionId The transaction ID.
         */
        public void setTransactionId(String transactionId) { 
            this.transactionId = transactionId; 
        }

        /**
         * Gets the transaction amount in cents.
         *
         * @return The amount in cents.
         */
        public long getAmountCents() { 
            return amountCents; 
        }
        
        /**
         * Sets the transaction amount in cents.
         *
         * @param amountCents The amount in cents.
         */
        public void setAmountCents(long amountCents) { 
            this.amountCents = amountCents; 
        }

        /**
         * Gets the currency code.
         *
         * @return The currency code.
         */
        public String getCurrency() { 
            return currency; 
        }
        
        /**
         * Sets the currency code.
         *
         * @param currency The currency code.
         */
        public void setCurrency(String currency) { 
            this.currency = currency; 
        }

        /**
         * Gets the transaction status.
         *
         * @return The status string.
         */
        public String getStatus() { 
            return status; 
        }
        
        /**
         * Sets the transaction status.
         *
         * @param status The status string.
         */
        public void setStatus(String status) { 
            this.status = status; 
        }

        /**
         * Gets the payment timestamp.
         *
         * @return The timestamp when payment was processed.
         */
        public Instant getPaidAt() { 
            return paidAt; 
        }
        
        /**
         * Sets the payment timestamp.
         *
         * @param paidAt The timestamp when payment was processed.
         */
        public void setPaidAt(Instant paidAt) { 
            this.paidAt = paidAt; 
        }

        /**
         * Gets the refund identifier.
         *
         * @return The refund ID, or null if not refunded.
         */
        public String getRefundId() { 
            return refundId; 
        }
        
        /**
         * Sets the refund identifier.
         *
         * @param refundId The refund ID.
         */
        public void setRefundId(String refundId) { 
            this.refundId = refundId; 
        }

        /**
         * Gets the refund timestamp.
         *
         * @return The timestamp when refund was processed, or null if not refunded.
         */
        public Instant getRefundedAt() { 
            return refundedAt; 
        }
        
        /**
         * Sets the refund timestamp.
         *
         * @param refundedAt The timestamp when refund was processed.
         */
        public void setRefundedAt(Instant refundedAt) { 
            this.refundedAt = refundedAt; 
        }
    }

    // --- Overrides ---

    /**
     * Returns a string representation of the Reservation.
     *
     * @return A string containing all reservation details including IDs, dates, and status.
     */
    @Override
    public String toString() {
        return "Reservation [id=" + id + ", user=" + user + ", roomId=" + room + ", checkIn=" + checkIn
                + ", checkOut=" + checkOut + ", guestCount=" + guestCount + ", totalPrice=" + totalPrice + ", status="
                + status + ", paymentIntentId=" + paymentIntentId + "]";
    }

    /**
     * Generates a hash code for this Reservation.
     * Based on all fields including IDs, dates, price, and payment info.
     *
     * @return The hash code.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((user == null) ? 0 : user.hashCode());
        result = prime * result + ((room == null) ? 0 : room.hashCode());
        result = prime * result + ((checkIn == null) ? 0 : checkIn.hashCode());
        result = prime * result + ((checkOut == null) ? 0 : checkOut.hashCode());
        result = prime * result + guestCount;
        long temp;
        temp = Double.doubleToLongBits(totalPrice);
        result = prime * result + (int) (temp ^ (temp >>> 32));
        result = prime * result + ((status == null) ? 0 : status.hashCode());
        result = prime * result + ((paymentIntentId == null) ? 0 : paymentIntentId.hashCode());
        return result;
    }

    /**
     * Checks if this Reservation is equal to another object.
     * Equality is determined by comparing all fields of the Reservation.
     *
     * @param obj The object to compare with.
     * @return True if the objects are equal; false otherwise.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Reservation other = (Reservation) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (user == null) {
            if (other.user != null)
                return false;
        } else if (!user.equals(other.user))
            return false;
        if (room == null) {
            if (other.room != null)
                return false;
        } else if (!room.equals(other.room))
            return false;
        if (checkIn == null) {
            if (other.checkIn != null)
                return false;
        } else if (!checkIn.equals(other.checkIn))
            return false;
        if (checkOut == null) {
            if (other.checkOut != null)
                return false;
        } else if (!checkOut.equals(other.checkOut))
            return false;
        if (guestCount != other.guestCount)
            return false;
        if (Double.doubleToLongBits(totalPrice) != Double.doubleToLongBits(other.totalPrice))
            return false;
        if (status != other.status)
            return false;
        if (paymentIntentId == null) {
            if (other.paymentIntentId != null)
                return false;
        } else if (!paymentIntentId.equals(other.paymentIntentId))
            return false;
        return true;
    }

    // --- Getters and Setters ---

    /**
     * Gets the unique identifier of the reservation.
     *
     * @return The MongoDB ObjectId as a String.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the reservation.
     *
     * @param id The new MongoDB ObjectId.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the User object associated with this reservation.
     * This is a transient field populated for frontend display.
     *
     * @return The User object, or null if not populated.
     */
    public User getUser() { 
        return user; 
    }
    
    /**
     * Sets the User object and synchronizes the userId field.
     *
     * @param user The User object to associate with this reservation.
     */
    public void setUser(User user) {
        this.user = user;
        if (user != null) this.userId = user.getId();
    }

    /**
     * Gets the Room object associated with this reservation.
     * This is a transient field populated for frontend display.
     *
     * @return The Room object, or null if not populated.
     */
    public Room getRoom() { 
        return room; 
    }
    
    /**
     * Sets the Room object and synchronizes the roomId field.
     *
     * @param room The Room object to associate with this reservation.
     */
    public void setRoom(Room room) {
        this.room = room;
        if (room != null) this.roomId = room.getId();
    }

    /**
     * Gets the user ID string.
     *
     * @return The user ID.
     */
    public String getUserId() { 
        return userId; 
    }
    
    /**
     * Sets the user ID string.
     *
     * @param userId The new user ID.
     */
    public void setUserId(String userId) { 
        this.userId = userId; 
    }
    
    /**
     * Gets the room ID string.
     *
     * @return The room ID.
     */
    public String getRoomId() { 
        return roomId; 
    }
    
    /**
     * Sets the room ID string.
     *
     * @param roomId The new room ID.
     */
    public void setRoomId(String roomId) { 
        this.roomId = roomId; 
    }

    /**
     * Gets the check-in date.
     *
     * @return The check-in date.
     */
    public LocalDate getCheckIn() {
        return checkIn;
    }

    /**
     * Sets the check-in date.
     *
     * @param checkIn The new check-in date.
     */
    public void setCheckIn(LocalDate checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * Gets the check-out date.
     *
     * @return The check-out date.
     */
    public LocalDate getCheckOut() {
        return checkOut;
    }

    /**
     * Sets the check-out date.
     *
     * @param checkOut The new check-out date.
     */
    public void setCheckOut(LocalDate checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * Gets the number of guests.
     *
     * @return The guest count.
     */
    public int getGuestCount() {
        return guestCount;
    }

    /**
     * Sets the number of guests.
     *
     * @param guestCount The new guest count.
     */
    public void setGuestCount(int guestCount) {
        this.guestCount = guestCount;
    }

    /**
     * Gets the total price of the reservation.
     *
     * @return The total price.
     */
    public double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the total price of the reservation.
     *
     * @param totalPrice The new total price.
     */
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Gets the current status of the reservation.
     *
     * @return The reservation status (e.g., CONFIRMED, CANCELLED).
     */
    public ReservationStatus getStatus() {
        return status;
    }

    /**
     * Sets the status of the reservation.
     *
     * @param status The new status.
     */
    public void setStatus(ReservationStatus status) {
        this.status = status;
    }

    /**
     * Gets the Stripe Payment Intent ID associated with this booking.
     *
     * @return The payment intent ID.
     */
    public String getPaymentIntentId() {
        return paymentIntentId;
    }

    /**
     * Sets the Stripe Payment Intent ID.
     *
     * @param paymentIntentId The new payment intent ID.
     */
    public void setPaymentIntentId(String paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }

    /**
     * Gets the payment status of the reservation.
     *
     * @return The payment status.
     */
    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the payment status of the reservation.
     *
     * @param paymentStatus The new payment status.
     */
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * Gets the payment transaction details.
     *
     * @return The payment transaction.
     */
    public PaymentTransaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the payment transaction details.
     *
     * @param transaction The new payment transaction.
     */
    public void setTransaction(PaymentTransaction transaction) {
        this.transaction = transaction;
    }

    /**
     * Gets the check-in timestamp.
     *
     * @return The check-in timestamp.
     */
    public Instant getCheckedInAt() {
        return checkedInAt;
    }

    /**
     * Sets the check-in timestamp.
     *
     * @param checkedInAt The new check-in timestamp.
     */
    public void setCheckedInAt(Instant checkedInAt) {
        this.checkedInAt = checkedInAt;
    }
}