package com.skillstorm.hotelreservationsystem.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

/**
 * Represents a category or configuration of rooms available in the hotel.
 * <p>
 * Unlike the {@code Room} class, which represents a specific physical door (e.g., "Room 101"),
 * this class defines the <i>type</i> of room (e.g., "Pro Gamer Suite", "Standard King").
 * It holds the metadata regarding pricing, capacity, amenities, and specific gaming hardware
 * available in that tier of room.
 * </p>
 * * @author SkillStorm
 * @version 1.0
 */
@Document(collection = "room_types")
public class RoomType {

    /**
     * The unique identifier for the room type.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The display name of the room type (e.g., "Ultimate Gamer Suite", "Co-Op Double").
     */
    private String name;

    /**
     * The base cost per night for this room type.
     */
    private double pricePerNight;
    
    // --- Bed Config ---

    /**
     * The number of beds in the room.
     */
    private int numBeds;

    /**
     * The size or type of the beds (e.g., "King", "Queen", "Twin").
     */
    private String typeBed;

    /**
     * The number of separate bedrooms within the suite.
     */
    private int numBeedroom; // kept variable name as-is from your snippet
    
    // --- Specs ---

    /**
     * The total area of the room in square feet.
     */
    private int squareFeet;

    /**
     * The maximum number of guests allowed to sleep in this room.
     */
    private int capacity;
    
    // --- Amenities ---

    /**
     * Indicates if the room includes a private jacuzzi.
     */
    private boolean hasJacuzzi;

    /**
     * Indicates if the room includes a kitchenette or full kitchen.
     */
    private boolean hasKitchen;
    
    // --- Gaming Gear (The unique stuff) ---

    /**
     * The tier level of the gaming PC provided (e.g., 1=Entry, 2=Mid-Range, 3=High-End/RTX 4090).
     */
    private int levelOfPc;

    /**
     * The number of gaming PC setups available in the room.
     */
    private int numPcs;

    /**
     * A list of gaming consoles available in the room (e.g., ["PS5", "Nintendo Switch"]).
     */
    private List<String> consoles;

    // --- Media ---

    /**
     * A list of URLs pointing to images of the room hosted on cloud storage (AWS S3).
     */
    private List<String> images; 

    // --- Overrides ---

    /**
     * Returns a string representation of the RoomType.
     *
     * @return A string containing all room type details including name, price, and specs.
     */
    @Override
    public String toString() {
        return "RoomType [id=" + id + ", name=" + name + ", pricePerNight=" + pricePerNight + ", numBeds=" + numBeds
                + ", typeBed=" + typeBed + ", numBeedroom=" + numBeedroom + ", squareFeet=" + squareFeet + ", capacity="
                + capacity + ", hasJacuzzi=" + hasJacuzzi + ", hasKitchen=" + hasKitchen + ", levelOfPc=" + levelOfPc
                + ", numPcs=" + numPcs + ", consoles=" + consoles + ", images=" + images + "]";
    }

    /**
     * Generates a hash code for this RoomType.
     * Based on all fields including specs, amenities, and gaming gear.
     *
     * @return The hash code.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        long temp;
        temp = Double.doubleToLongBits(pricePerNight);
        result = prime * result + (int) (temp ^ (temp >>> 32));
        result = prime * result + numBeds;
        result = prime * result + ((typeBed == null) ? 0 : typeBed.hashCode());
        result = prime * result + numBeedroom;
        result = prime * result + squareFeet;
        result = prime * result + capacity;
        result = prime * result + (hasJacuzzi ? 1231 : 1237);
        result = prime * result + (hasKitchen ? 1231 : 1237);
        result = prime * result + levelOfPc;
        result = prime * result + numPcs;
        result = prime * result + ((consoles == null) ? 0 : consoles.hashCode());
        result = prime * result + ((images == null) ? 0 : images.hashCode());
        return result;
    }

    /**
     * Checks if this RoomType is equal to another object.
     * Equality is determined by comparing all fields.
     *
     * @param obj The object to compare with.
     * @return True if the objects are equal; false otherwise.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        RoomType other = (RoomType) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (Double.doubleToLongBits(pricePerNight) != Double.doubleToLongBits(other.pricePerNight))
            return false;
        if (numBeds != other.numBeds)
            return false;
        if (typeBed == null) {
            if (other.typeBed != null)
                return false;
        } else if (!typeBed.equals(other.typeBed))
            return false;
        if (numBeedroom != other.numBeedroom)
            return false;
        if (squareFeet != other.squareFeet)
            return false;
        if (capacity != other.capacity)
            return false;
        if (hasJacuzzi != other.hasJacuzzi)
            return false;
        if (hasKitchen != other.hasKitchen)
            return false;
        if (levelOfPc != other.levelOfPc)
            return false;
        if (numPcs != other.numPcs)
            return false;
        if (consoles == null) {
            if (other.consoles != null)
                return false;
        } else if (!consoles.equals(other.consoles))
            return false;
        if (images == null) {
            if (other.images != null)
                return false;
        } else if (!images.equals(other.images))
            return false;
        return true;
    }

    // --- Getters and Setters ---

    /**
     * Gets the unique identifier of the room type.
     *
     * @return The MongoDB ObjectId as a String.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the room type.
     *
     * @param id The new MongoDB ObjectId.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the display name of the room type.
     *
     * @return The room type name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of the room type.
     *
     * @param name The new room type name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the price per night.
     *
     * @return The price per night.
     */
    public double getPricePerNight() {
        return pricePerNight;
    }

    /**
     * Sets the price per night.
     *
     * @param pricePerNight The new price per night.
     */
    public void setPricePerNight(double pricePerNight) {
        this.pricePerNight = pricePerNight;
    }

    /**
     * Gets the number of beds.
     *
     * @return The number of beds.
     */
    public int getNumBeds() {
        return numBeds;
    }

    /**
     * Sets the number of beds.
     *
     * @param numBeds The new number of beds.
     */
    public void setNumBeds(int numBeds) {
        this.numBeds = numBeds;
    }

    /**
     * Gets the type of bed (e.g., King, Queen).
     *
     * @return The bed type.
     */
    public String getTypeBed() {
        return typeBed;
    }

    /**
     * Sets the type of bed.
     *
     * @param typeBed The new bed type.
     */
    public void setTypeBed(String typeBed) {
        this.typeBed = typeBed;
    }

    /**
     * Gets the number of bedrooms.
     *
     * @return The number of bedrooms.
     */
    public int getNumBeedroom() {
        return numBeedroom;
    }

    /**
     * Sets the number of bedrooms.
     *
     * @param numBeedroom The new number of bedrooms.
     */
    public void setNumBeedroom(int numBeedroom) {
        this.numBeedroom = numBeedroom;
    }

    /**
     * Gets the square footage of the room.
     *
     * @return The square footage.
     */
    public int getSquareFeet() {
        return squareFeet;
    }

    /**
     * Sets the square footage of the room.
     *
     * @param squareFeet The new square footage.
     */
    public void setSquareFeet(int squareFeet) {
        this.squareFeet = squareFeet;
    }

    /**
     * Gets the guest capacity of the room.
     *
     * @return The max number of guests.
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Sets the guest capacity of the room.
     *
     * @param capacity The new max number of guests.
     */
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    /**
     * Checks if the room has a jacuzzi.
     *
     * @return True if a jacuzzi is present.
     */
    public boolean isHasJacuzzi() {
        return hasJacuzzi;
    }

    /**
     * Sets the jacuzzi availability.
     *
     * @param hasJacuzzi True if a jacuzzi is present.
     */
    public void setHasJacuzzi(boolean hasJacuzzi) {
        this.hasJacuzzi = hasJacuzzi;
    }

    /**
     * Checks if the room has a kitchen.
     *
     * @return True if a kitchen is present.
     */
    public boolean isHasKitchen() {
        return hasKitchen;
    }

    /**
     * Sets the kitchen availability.
     *
     * @param hasKitchen True if a kitchen is present.
     */
    public void setHasKitchen(boolean hasKitchen) {
        this.hasKitchen = hasKitchen;
    }

    /**
     * Gets the performance level of the provided PC.
     *
     * @return The PC tier level (e.g., 1, 2, or 3).
     */
    public int getLevelOfPc() {
        return levelOfPc;
    }

    /**
     * Sets the performance level of the provided PC.
     *
     * @param levelOfPc The new PC tier level.
     */
    public void setLevelOfPc(int levelOfPc) {
        this.levelOfPc = levelOfPc;
    }

    /**
     * Gets the number of PCs in the room.
     *
     * @return The number of PCs.
     */
    public int getNumPcs() {
        return numPcs;
    }

    /**
     * Sets the number of PCs in the room.
     *
     * @param numPcs The new number of PCs.
     */
    public void setNumPcs(int numPcs) {
        this.numPcs = numPcs;
    }

    /**
     * Gets the list of available gaming consoles.
     *
     * @return A list of console names.
     */
    public List<String> getConsoles() {
        return consoles;
    }

    /**
     * Sets the list of available gaming consoles.
     *
     * @param consoles The new list of consoles.
     */
    public void setConsoles(List<String> consoles) {
        this.consoles = consoles;
    }

    /**
     * Gets the list of image URLs for the room.
     *
     * @return A list of S3 image URLs.
     */
    public List<String> getImages() {
        return images;
    }

    /**
     * Sets the list of image URLs for the room.
     *
     * @param images The new list of S3 image URLs.
     */
    public void setImages(List<String> images) {
        this.images = images;
    }
}