package com.skillstorm.hotelreservationsystem.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a physical room within the hotel reservation system.
 * <p>
 * This class maps to the "rooms" collection in MongoDB. It stores the specific attributes
 * of a single room unit (such as room number and current occupancy status) and links
 * to a {@code RoomTypeId} definition for broader categorization and pricing.
 * </p>
 * * @author SkillStorm
 * @version 1.0
 */
@Document(collection = "rooms")
public class Room {
    
    public Room() {
    }

    public Room(String roomNumber, String roomTypeId, boolean accessible, boolean petFriendly, boolean nonSmoking,
            boolean occupied, List<UnavailableDate> unavailableDates) {
        this.roomNumber = roomNumber;
        this.roomTypeId = roomTypeId;
        this.accessible = accessible;
        this.petFriendly = petFriendly;
        this.nonSmoking = nonSmoking;
        this.occupied = occupied;
        this.unavailableDates = unavailableDates;
    }

    /**
     * The unique identifier for the room.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The physical number or name of the room (e.g., "101", "Suite A").
     */
    private String roomNumber;


    @Field("roomTypeId") 
    @JsonIgnore 
    private String roomTypeId;

    /**
     * The room type object
     * 
     */
    @Transient
    private RoomType roomType;
    private String roomTypeId;
    
    /**
     * Indicates if the room meets accessibility standards (ADA compliant).
     */
    private boolean accessible;

    /**
     * Indicates if pets are allowed in this room.
     */
    private boolean petFriendly;

    /**
     * Indicates if this is a non-smoking room.
     */
    private boolean nonSmoking;

    /**
     * The current real-time occupancy status of the room.
     * True if a guest is currently checked in; false otherwise.
     */
    private boolean occupied;

    /**
     * A list of date ranges during which this room cannot be booked.
     * This includes confirmed reservations and maintenance blocks.
     */
    private List<UnavailableDate> unavailableDates;

    // --- Inner Class for Dates ---

    /**
     * Represents a specific date range (start to end) during which a room is unavailable.
     * Used to prevent double-booking.
     */
    public static class UnavailableDate {
        
        /**
         * The start date of the unavailability range (inclusive).
         */
        private LocalDate start;

        /**
         * The end date of the unavailability range (inclusive).
         */
        private LocalDate end;

        /**
         * Constructs a new UnavailableDate range.
         *
         * @param start The start date of the range.
         * @param end   The end date of the range.
         */
        public UnavailableDate(LocalDate start, LocalDate end) {
            this.start = start;
            this.end = end;
        }

        /**
         * Gets the start date of the unavailable range.
         *
         * @return The start date.
         */
        public LocalDate getStart() {
            return start;
        }

        /**
         * Sets the start date of the unavailable range.
         *
         * @param start The new start date.
         */
        public void setStart(LocalDate start) {
            this.start = start;
        }

        /**
         * Gets the end date of the unavailable range.
         *
         * @return The end date.
         */
        public LocalDate getEnd() {
            return end;
        }

        /**
         * Sets the end date of the unavailable range.
         *
         * @param end The new end date.
         */
        public void setEnd(LocalDate end) {
            this.end = end;
        }

        /**
         * Returns a string representation of the UnavailableDate.
         *
         * @return A string containing the start and end dates.
         */
        @Override
        public String toString() {
            return "UnavailableDate [start=" + start + ", end=" + end + "]";
        }

        /**
         * Generates a hash code for this date range.
         * Based on the start and end dates.
         *
         * @return The hash code.
         */
        @Override
        public int hashCode() {
            final int prime = 31;
            int result = 1;
            result = prime * result + ((start == null) ? 0 : start.hashCode());
            result = prime * result + ((end == null) ? 0 : end.hashCode());
            return result;
        }

        /**
         * Checks if this UnavailableDate is equal to another object.
         * Two ranges are considered equal if they have the same start and end dates.
         *
         * @param obj The object to compare with.
         * @return True if the objects are equal; false otherwise.
         */
        @Override
        public boolean equals(Object obj) {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            UnavailableDate other = (UnavailableDate) obj;
            if (start == null) {
                if (other.start != null)
                    return false;
            } else if (!start.equals(other.start))
                return false;
            if (end == null) {
                if (other.end != null)
                    return false;
            } else if (!end.equals(other.end))
                return false;
            return true;
        }
    }

    // --- Room Methods ---

    /**
     * Returns a string representation of the Room.
     *
     * @return A string containing the room's ID, number, type, attributes, and unavailable dates.
     */
    @Override
    public String toString() {
        return "Room [id=" + id + ", roomNumber=" + roomNumber + ", roomTypeId=" + roomTypeId + ", accessible="
                + accessible + ", petFriendly=" + petFriendly + ", nonSmoking=" + nonSmoking + ", occupied=" + occupied
                + ", unavailableDates=" + unavailableDates + "]";
    }

    /**
     * Generates a hash code for this Room.
     * Based on all fields including ID, room number, type, attributes, and dates.
     *
     * @return The hash code.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((roomNumber == null) ? 0 : roomNumber.hashCode());
        result = prime * result + ((roomTypeId == null) ? 0 : roomTypeId.hashCode());
        result = prime * result + (accessible ? 1231 : 1237);
        result = prime * result + (petFriendly ? 1231 : 1237);
        result = prime * result + (nonSmoking ? 1231 : 1237);
        result = prime * result + (occupied ? 1231 : 1237);
        result = prime * result + ((unavailableDates == null) ? 0 : unavailableDates.hashCode());
        return result;
    }

    /**
     * Checks if this Room is equal to another object.
     * Equality is determined by comparing all fields of the Room.
     *
     * @param obj The object to compare with.
     * @return True if the objects are equal; false otherwise.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Room other = (Room) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (roomNumber == null) {
            if (other.roomNumber != null)
                return false;
        } else if (!roomNumber.equals(other.roomNumber))
            return false;
        if (roomTypeId == null) {
            if (other.roomTypeId != null)
                return false;
        } else if (!roomTypeId.equals(other.roomTypeId))
            return false;
        if (accessible != other.accessible)
            return false;
        if (petFriendly != other.petFriendly)
            return false;
        if (nonSmoking != other.nonSmoking)
            return false;
        if (occupied != other.occupied)
            return false;
        if (unavailableDates == null) {
            if (other.unavailableDates != null)
                return false;
        } else if (!unavailableDates.equals(other.unavailableDates))
            return false;
        return true;
    }


    @JsonProperty("roomTypeId")
    public RoomType getRoomType() {
        return roomType;
    }

    public void setRoomType(RoomType roomType) {
        this.roomType = roomType;
        if (roomType != null) {
            this.roomTypeId = roomType.getId();
        }
    }

    /**
     * Gets the unique identifier of the room.
     *
     * @return The MongoDB ObjectId as a String.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the room.
     *
     * @param id The new MongoDB ObjectId.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the room number.
     *
     * @return The room number (e.g., "101").
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the room number.
     *
     * @param roomNumber The new room number.
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * Gets the Room Type
     *
     * @return The RoomType.
     */
    public String getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * Sets the Room Type
     * @param roomType
     */
    public void setRoomTypeID(String roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    /**
     * Checks if the room is accessible (ADA compliant).
     *
     * @return True if the room is accessible; false otherwise.
     */
    public boolean isAccessible() {
        return accessible;
    }

    /**
     * Sets the accessibility status of the room.
     *
     * @param accessible True to mark as accessible.
     */
    public void setAccessible(boolean accessible) {
        this.accessible = accessible;
    }

    /**
     * Checks if the room is pet-friendly.
     *
     * @return True if pets are allowed; false otherwise.
     */
    public boolean isPetFriendly() {
        return petFriendly;
    }

    /**
     * Sets the pet-friendly status of the room.
     *
     * @param petFriendly True to allow pets.
     */
    public void setPetFriendly(boolean petFriendly) {
        this.petFriendly = petFriendly;
    }

    /**
     * Checks if the room is non-smoking.
     *
     * @return True if smoking is prohibited; false otherwise.
     */
    public boolean isNonSmoking() {
        return nonSmoking;
    }

    /**
     * Sets the non-smoking status of the room.
     *
     * @param nonSmoking True to mark as non-smoking.
     */
    public void setNonSmoking(boolean nonSmoking) {
        this.nonSmoking = nonSmoking;
    }

    /**
     * Checks if the room is currently physically occupied.
     *
     * @return True if occupied; false otherwise.
     */
    public boolean isOccupied() {
        return occupied;
    }

    /**
     * Sets the current occupancy status of the room.
     *
     * @param occupied True to mark as occupied.
     */
    public void setOccupied(boolean occupied) {
        this.occupied = occupied;
    }

    /**
     * Gets the list of dates when the room is unavailable.
     *
     * @return A list of UnavailableDate objects.
     */
    public List<UnavailableDate> getUnavailableDates() {
        return unavailableDates;
    }

    /**
     * Sets the list of dates when the room is unavailable.
     *
     * @param unavailableDates The new list of unavailable dates.
     */
    public void setUnavailableDates(List<UnavailableDate> unavailableDates) {
        this.unavailableDates = unavailableDates;
    }
}